[build]
builder = "DOCKERFILE"
dockerfilePath = "app.dockerfile"

[deploy]
startCommand = "./entrypoint.sh"
healthcheckPath = "/api/config"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

